[package]
name = "psbt_compress"
version = "0.1.0"
authors = ["Stepan Snigirev <snigirev.stepan@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.68"
bitcoin = { version="0.26.0", features=["base64"] }